# Generated by Django 2.2.5 on 2020-01-23 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('videofile', models.FileField(upload_to='videobooks')),
                ('coverimages', models.FileField(upload_to='coverimages')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
                ('booktap_price', models.IntegerField()),
                ('book_rated', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoBookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBookReviewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField()),
                ('rating', models.IntegerField()),
                ('ebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoBook.VideoBook')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='videobook',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoBook.VideoBookType'),
        ),
    ]
