# Generated by Django 2.2.5 on 2019-10-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_failorders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoOfBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_books', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoOfCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_customers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoOfSuppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suppliers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuccessOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_successorders', models.IntegerField()),
            ],
        ),
    ]
