# Generated by Django 2.2.5 on 2019-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_count', models.IntegerField()),
                ('customer_count', models.IntegerField()),
                ('supplier_count', models.IntegerField()),
                ('order_success_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FailOrders',
        ),
        migrations.DeleteModel(
            name='NoOfBooks',
        ),
        migrations.DeleteModel(
            name='NoOfCustomer',
        ),
        migrations.DeleteModel(
            name='NoOfSuppliers',
        ),
        migrations.DeleteModel(
            name='SuccessOrders',
        ),
    ]
