# Generated by Django 2.2.5 on 2019-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20190926_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signin',
            name='is_suppliers',
            field=models.BooleanField(default=False),
        ),
    ]
