# Generated by Django 2.2.5 on 2019-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20191009_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='is_customer',
            field=models.BooleanField(),
        ),
    ]
