# Generated by Django 2.2.5 on 2019-10-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_auto_20191010_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='is_customer',
            field=models.BooleanField(),
        ),
    ]
