# Generated by Django 2.2.5 on 2019-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_auto_20191011_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='is_suppliers',
            field=models.BooleanField(),
        ),
    ]
