# Generated by Django 2.2.5 on 2019-10-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0009_auto_20191021_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
