# Generated by Django 2.2.5 on 2019-10-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_auto_20191021_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
