# Generated by Django 2.2.5 on 2019-10-22 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro', '0011_auto_20191021_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20)),
                ('is_end_user', models.BooleanField(default=False)),
                ('agree', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField()),
                ('is_suppliers', models.BooleanField()),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
