# Generated by Django 2.2.5 on 2019-10-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signin',
            options={'default_permissions': ('change', 'add', 'delete', 'view')},
        ),
    ]
