# Generated by Django 2.2.5 on 2019-10-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0014_auto_20191022_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
