# Generated by Django 2.2.5 on 2019-10-23 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro', '0015_auto_20191022_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='password2',
        ),
        migrations.AddField(
            model_name='signin',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
