# Generated by Django 2.2.5 on 2019-10-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0016_auto_20191023_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='user',
        ),
    ]
