# Generated by Django 2.2.5 on 2019-11-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0019_remove_signin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
