# Generated by Django 2.2.5 on 2019-12-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0021_remove_signin_is_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
