# Generated by Django 2.2.5 on 2019-12-04 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro', '0022_auto_20191203_0717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ElectronicBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_search', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElectronicBook.ElectronicBook')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('commission', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('ebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElectronicBook.ElectronicBook')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Signin')),
            ],
        ),
    ]
