# Generated by Django 2.2.5 on 2019-10-09 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro', '0004_auto_20191009_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('commission', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Signin')),
            ],
        ),
    ]
