# Generated by Django 2.2.5 on 2020-01-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicBook', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerElectronicBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ElectronicBook.ElectronicBook')),
            ],
        ),
    ]
