# Generated by Django 2.2.5 on 2019-10-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookreviewrecord'),
        ('customer', '0002_customersearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
    ]
