# Generated by Django 2.2.5 on 2019-10-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_auto_20191011_0755'),
        ('customer', '0005_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pro.Signin'),
            preserve_default=False,
        ),
    ]
