# Generated by Django 2.2.5 on 2019-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customerreview_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
