# Generated by Django 2.2.5 on 2019-11-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20191112_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.EBook'),
        ),
    ]
