# Generated by Django 2.2.5 on 2019-11-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20191112_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
