# Generated by Django 2.2.5 on 2019-11-14 08:55

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20191112_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
