# Generated by Django 2.2.5 on 2019-10-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.BookType'),
            preserve_default=False,
        ),
    ]
