# Generated by Django 2.2.5 on 2019-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookreviewrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default=1, upload_to='book'),
            preserve_default=False,
        ),
    ]
