# Generated by Django 2.2.5 on 2019-11-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_ebook_langauges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='price',
        ),
    ]
