# Generated by Django 2.2.5 on 2019-11-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_ebook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
