# Generated by Django 2.2.5 on 2019-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_ebook_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviewrecord',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
