# Generated by Django 2.2.5 on 2019-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_bookreviewrecord_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook',
            name='format',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook',
            name='isbn',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
