# Generated by Django 2.2.5 on 2019-11-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20191105_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviewrecord',
            name='ebook_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.EBook'),
            preserve_default=False,
        ),
    ]
