# Generated by Django 2.2.5 on 2019-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_bookreviewrecord_ebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='book_rated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
