# Generated by Django 2.2.5 on 2019-10-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
